### ISSUE TITLE
Lab member page: undergrads shouldn't have BSc beside their names

### ISSUE THREAD

**Issue by emilyolafson** [CoBrALab/CobraLab.github.io#16]
With the exception of me (Emily Olafson), nobody has graduated yet!

**Comment by emilyolafson** [comment]
Actually, this is true of the master's and PhD students too.. might be best to say "PhD candidate/student" or "Master's candidate/student" for those who are in the process of completing their degrees

**Comment by ValiquetteVanessa** [comment]
Swapna suggested the same thing as well. Will make the change. Thank you :)
