### ISSUE TITLE
Big yellow buttons?

### ISSUE THREAD

**Issue by lani1** [CoBrALab/CobraLab.github.io#20]
This may just be stylistic, but I expected the big yellow rectangles on the front page to be links I could click to read more about our work on the disorder. Is this still just a work in progress, or are they there for decoration?

**Comment by gdevenyi** [comment]
Was wondering the same thing.

**Comment by ValiquetteVanessa** [comment]
Good point. I will see if I can link it to anything relevant. If not, I will modify the design of it. Thank you :)
