### ISSUE TITLE
Add missing alumni?

### ISSUE THREAD

**Issue by gdevenyi** [CoBrALab/CobraLab.github.io#4]
We're probably missing some names to put in the alumni list, get them?

**Comment by mallarchak** [comment]
How are we defining alumni?  CAMH version of this lab?

mallar

**Comment by gdevenyi** [comment]
My working definition is "anyone who worked for you and doesn't anymore"

**Comment by mallarchak** [comment]
got

Jon Pipitone
Joseph Viviano
David Rotenberg

I think that would do it.  I can add more if need be.

mallar

**Comment by gdevenyi** [comment]
Can you request a bio from them via email (CC me)

**Comment by gdevenyi** [comment]
Sorted
